# Generated by Django 2.2.3 on 2019-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autor'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='date_published',
            field=models.DateField(verbose_name='Fecha Publicado'),
        ),
    ]
