# Generated by Django 2.2.3 on 2019-08-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20190802_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='date_create',
            field=models.DateField(auto_now=True, verbose_name='Fecha Creacion'),
        ),
        migrations.AddField(
            model_name='libro',
            name='date_create',
            field=models.DateField(auto_now=True, verbose_name='Fecha Creacion'),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor_id',
            field=models.ManyToManyField(to='libro.Autor'),
        ),
    ]
