# Generated by Django 2.2.3 on 2019-08-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_auto_20190802_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='Nacionalidad'),
        ),
    ]
